name: Example Workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a script that uses jq
        run: |
          #!/usr/bin/env bash
          JSON='{"key":"value"}'
          echo "$JSON" | jq '.key'
